name: Main
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Upload build artifacts
        uses: actions/cache@v2
        with:
          path: ./packages
          key: build-packages-${{ github.sha }}

      - name: Run typings script
        run: yarn types

      - name: Run build script
        run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Fetch build artifacts
        uses: actions/cache@v2
        with:
          path: ./packages
          key: build-packages-${{ github.sha }}

      - name: Run tests
        run: yarn test

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - test
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Fetch build artifacts
        uses: actions/cache@v2
        with:
          path: ./packages
          key: build-packages-${{ github.sha }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
