name: Wiki
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
    tags-ignore:
      - '*'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docs:
    name: Wiki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push documentation to wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WIKI_TOKEN }}
        run: |
          git config --global user.email "dev@chialab.io"
          git config --global user.name "chialab-io"
          git clone https://${GITHUB_TOKEN}@github.com/chialab/rna.wiki.git wiki
          rm -rf wiki/*.md
          cp -rf docs/* wiki
          git -C wiki add .
          git -C wiki diff-index --quiet HEAD || git -C wiki commit -m "Update wiki from workflow"
          git -C wiki push --set-upstream origin master --follow-tags
